server:
  port: 15000
# Spring配置
spring:
  # 链路追踪配置
  zipkin:
    base-url: http://192.168.0.100:9411
    sleuth:
      sampler:
        probability: 1
  # Sentinel配置
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.0.100:884880
        port: 8719
  # Redis配置
  redis:
    host: 192.168.0.100
    password: 123456
    timeout: 30000ms
    database: 15
  # MVC配置
  mvc:
    log-request-details: true
  # DevTools配置
  devtools:
    restart:
      exclude: classpath:static/*
      log-condition-evaluation-delta: false
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 日志配置
logging:
  level:
    org.springframework.web: debug