# 服务器配置
server:
  port: 10000
# Spring配置
spring:
  # 服务名称
  application:
    name: MICRO-SERVICE-GATEWAY
  # MVC配置
  mvc:
    log-request-details: true
  # DevTools配置
  devtools:
    restart:
      exclude: classpath:static/*
      log-condition-evaluation-delta: false
  # Cloud配置
  cloud:
    # Nacos配置
    nacos:
      discovery:
        server-addr: development.machine-geek.cn:8848
    # Gateway配置
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account_route
          uri: lb://MICRO-SERVICE-ACCOUNT
          predicates:
            - Path=/account/**
        - id: role_route
          uri: lb://MICRO-SERVICE-ROLE
          predicates:
            - Path=/role/**
        - id: permission_route
          uri: lb://MICRO-SERVICE-PERMISSION
          predicates:
            - Path=/permission/**
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 日志配置
logging:
  level:
    org.springframework.web: debug