# Mybatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# Spring配置
spring:
  # 链路追踪配置
  zipkin:
    base-url: http://192.168.0.100:9411
    sleuth:
      sampler:
        probability: 1
  # Sentinel配置
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.0.100:8080
        port: 8719
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.100:3306/micro_service?useSSL=false&&serverTimezone=GMT%2B8&useInformationSchema=true
    username: root
    password: 123456
    druid:
      connection-init-sqls: set names utf8mb4
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filter:
        config:
          enabled: true
      web-stat-filter:
        enabled: true
  # Redis配置
  redis:
    host: 192.168.0.100
    password: 123456
    timeout: 30000ms
    database: 15
  # MVC配置
  mvc:
    log-request-details: true
  # DevTools配置
  devtools:
    restart:
      exclude: classpath:static/*
      log-condition-evaluation-delta: false
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
# Dubbo配置
dubbo:
  registry:
    address: nacos://192.168.0.100:80
# 日志配置
logging:
  level:
    org.springframework.web: debug